// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpcugujnfpaknnhzpnkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwY3VndWpuZnBha25uaHpwbmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjE2MjUsImV4cCI6MjA2MDY5NzYyNX0.FAnQO9tkOgN0as813Qf6jA35JWmUaS0Y5nUDDdiQhJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);